### ISSUE TITLE
It's not possible to snap on vertex without a face.

### ISSUE THREAD

**Issue by hilth-augusto** [s-leger/blender_cad_transforms#10]
The snaps on this amazing tool doesn't work on on vertex without faces. 
This is a problem because if we import a dxf file we can't snap on the edges to start the modeling process. 
[snap issue.zip](https://github.com/s-leger/blender_cad_transforms/files/4753771/snap.issue.zip)

**Comment by s-leger** [comment]
Turn your dxf into curves, so they are sanp-able.
At this time mesh without faces are not snap-able as mesh may quickly become huge and pure open gl snap through python is slow.
