### ISSUE TITLE
Error install Mac M1

### ISSUE THREAD

**Issue by jikometrix** [s-leger/blender_cad_transforms#101]
Hello, 
I get an error when installing the addon. Mac M1 OS 13.3.1 blender 3.5.1

<img width="1419" alt="Screenshot 2023-05-02 at 3 39 24 PM" src="https://user-images.githubusercontent.com/56171052/235781064-6e0f6119-6059-4b86-87ec-53708e49f8a3.png">

**Comment by jikometrix** [comment]
I was trying to install 0.9.5 CAD transform.

**Comment by danouuuu** [comment]
same issue for me...

**Comment by s-leger** [comment]
https://github.com/s-leger/blender_cad_transforms/issues/97#issuecomment-1490556657
