### ISSUE TITLE
Cad Transform will not install on blender 3.6 on mac air m2

### ISSUE THREAD

**Issue by jromania** [s-leger/blender_cad_transforms#106]
I get the following stack trace.  It failed slcad_transform_0.95.0 and then I tried slcad_transform_0.0.9_beta and had the same result.

<img width="814" alt="Screenshot 2023-07-25 at 10 25 46 PM" src="https://github.com/s-leger/blender_cad_transforms/assets/126221332/b2940def-aaf6-4cf6-a609-e6328a284e53">

Thanks!

**Comment by NoahCodeGG** [comment]
I also have the same problem on mac pro m1.

**Comment by s-leger** [comment]
https://github.com/s-leger/blender_cad_transforms/issues/97#issuecomment-1490556657
