### ISSUE TITLE
Shader compilation error when activating on macOS ARM64

### ISSUE THREAD

**Issue by eliezedeck** [s-leger/blender_cad_transforms#109]
Hi,

I'm on an M1 Max macos, and I cannot activate the addon on the 3.6.2 version of Blender. I have this error:
<img width="872" alt="CleanShot 2023-09-06 at 09 04 32@2x" src="https://github.com/s-leger/blender_cad_transforms/assets/7553916/84738908-43e3-4b88-a724-14c012ce3575">

Using the version 0.95.0 ZIP file.

What am I missing? and how can I make it work?

Thanks.

**Comment by tommyschnabel** [comment]
+1 to this

**Comment by s-leger** [comment]
https://github.com/s-leger/blender_cad_transforms/issues/97#issuecomment-1490556657
