### ISSUE TITLE
Snapping doesn't work in 2D (without faces) in Version 0.95.0

### ISSUE THREAD

**Issue by Chantico360** [s-leger/blender_cad_transforms#113]
Hello,

first of all.. thanks for the great addon! I'm learning blender using the Tutorials from Maker Tales and found a problem with the Addon in Version 0.95.0. The older version 0.93.2.beta.3 works.

If you create an object without a face (simple square in 2D) you cannot select or snap to anything (vertex, edge) other than the origin. It works in the older version.

Example:
![blender_EtKTqrveH4](https://github.com/s-leger/blender_cad_transforms/assets/108299069/3a7464ff-0a14-48f0-92ae-c77f19d10c2f)

I cannot snap-select any vertex or edge in the example. If I create faces, it works. I'm using Blender 3.6 LTS (3.6.7.0)

Regards,
Tobias

**Comment by s-leger** [comment]
Broken by blender api changes.
Made a complete refactory from scratch to handle this properly - CAD Transform 2.0 for blender 3.3+ / 4+.
it is available on gumroad's store 
[CAD Transform 2.0](https://blender-archipack.gumroad.com/l/emiwtw)

**Comment by Chantico360** [comment]
Thanks for your answer. I already bought CAD Transform 2.0 and I'm using 2.0.4 with Blender LTS 3.6.8.0. It works better in 2.0, but not as expected (am I using it wrong?).

Same shape like in the initial comment. It works on the outer edges, but not in the middle. If I create faces, the snapping works on the middle vertext. 

Form with all vertex are correct linked:
![blender_uu3kriJ9LB](https://github.com/s-leger/blender_cad_transforms/assets/108299069/20461233-4507-43b4-9173-eb67893a3776)

Outer vertex snapping works:
![blender_LzAHzro9Q6](https://github.com/s-leger/blender_cad_transforms/assets/108299069/af4d0d36-1672-4b05-ac71-058027382f1a)

Middle vertex won't snap:
![blender_97RYqYYsKX](https://github.com/s-leger/blender_cad_transforms/assets/108299069/072a305c-6d38-434d-a3ed-7783c926a93a)

Middle vertex snap with faces:

![blender_Rbf1geqomL](https://github.com/s-leger/blender_cad_transforms/assets/108299069/ac9f0e3e-884d-466d-92ff-4ba5fdf90310)

**Comment by s-leger** [comment]
In 2.0, you must enable snap to "Isolated elements" (rightmost snap option) in order to snap to edges / vertex not linked to faces.
It is disabled by default as it may be a bit slow with huge mesh objects.

Other points are working as they are located right on bounding box so basically you are snapping to bound box.

**Comment by Chantico360** [comment]
Thanks, that does the trick. Just one flaw: if I enable it during a operation (e.g. "G-"Key) it won't work until I restart the operation. That denies changing the snapping while operation (that was cool feature).

**Comment by s-leger** [comment]
You may alter other snap options while running, but this one needs to be set first as it does affect mesh object initialization. You may alter snap options in preferences so it is always enabled.

**Comment by Chantico360** [comment]
Ah okay. Thanks for the help and for the great addon!
