### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by iGhostENT** [s-leger/blender_cad_transforms#114]
I am pretty new and I am trying to activate the addon but this error pops up?

ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '2D_UNIFORM_COLOR'

**Comment by s-leger** [comment]
For a blender 4.x compatible release, you may download CAD Transform 2.0
https://blender-archipack.gumroad.com/l/emiwtw
