### ISSUE TITLE
Fractional unit behavior?

### ISSUE THREAD

**Issue by bertabus** [s-leger/blender_cad_transforms#115]
Is this expected behavior?

Unit scale set to 0.001 shows angles of 45 as 0.045, see screenshot
![fractional_Degrees](https://github.com/s-leger/blender_cad_transforms/assets/88117137/6e473e39-1ea0-4ed8-aa6b-23592c002c40)

after adjusting units to 1.00 it's accurate as 45
![AccurateScale](https://github.com/s-leger/blender_cad_transforms/assets/88117137/a1e97f9b-c80a-4946-bff5-df07e1199373)

**Comment by s-leger** [comment]
No, it is a bug.

**Comment by s-leger** [comment]
Fixed in 2.0.4
