### ISSUE TITLE
[REQUEST] Copy the object with move/rotate + Array from move/rotate

### ISSUE THREAD

**Issue by bzqp** [s-leger/blender_cad_transforms#17]
Hello!

I'm not sure if that would be possible, but coming from Sketchup/Rhino I would welcome an option to copy the objects with move/rotate tool.

In SketchUp by default when you move/rotate the object and them press "CTRL" it automatically makes a duplicate of the object at the transformation destination.

What is more - it allows you to make an array of the object after copying it. You just type the number of the objects with "/" or "x":
    / n (duplicates n objects inbetween the origin and destination)
    x n (duplicates n objects after the destination with transformation value)
As in the attached image:
![move rotate array2](https://user-images.githubusercontent.com/62249603/84910784-985da880-b0b7-11ea-831d-e2c91876744f.jpg)

It works similarly for rotation.

These features would be lifesavers for me and would fix my Blender workflow.
Best Regards and thanks for the plugin!

**Comment by Gadget2020** [comment]
I was going to write a request following similar lines:
Checkbox to "Apply transform to duplicate" (and sub checkbox to "merge geometry")

The array function would be cool, with the option of the array being an array of "Linked Duplicates" if in object mode.
