### ISSUE TITLE
Scaling a drag dropped image

### ISSUE THREAD

**Issue by BW2001** [s-leger/blender_cad_transforms#19]
Drag dropped an image in (Blender 2.82) top view, invoke CAD Transform, set face snapping, scale, drag pos1 to pos 2 and hit ESC -see below. Also the displayed axes didn't align with the two positions given.

![scale then escape](https://user-images.githubusercontent.com/61478602/86582679-e9a3de00-bf79-11ea-9b41-1cfd473b41b4.png)

**Comment by s-leger** [comment]
Thank you for reporting, 
looks like Image object is not properly supported, will take a look at this issue for next release.

**Comment by s-leger** [comment]
Fixed in 0.0.9
https://blenderartists.org/t/cad-like-transform/1226197/253
