### ISSUE TITLE
Proportional scaling a face in edit mode in blender 

### ISSUE THREAD

**Issue by stillpointx** [s-leger/blender_cad_transforms#20]
Proportional scaling a face in edit mode in blender 

**Describe the Issue**
When constraining different axis I can't do Proportional scaling of a face in edit mode in Blender 2.83.  I'm trying to scale it so I can just type in the value of the top face of (0.5 mm across).  I tried constraining and not constraining the face on the axis of x,y,z and several combinations of those but the face does not do proportionally scale.

**To Reproduce**

### Animated gif of what I'm trying to get using CAD Transforms ad-don by just typing in a value like .65
![vokoscreen-2020-07-09_00-15-45](https://user-images.githubusercontent.com/28985314/86996700-4f5eb880-c17a-11ea-9e90-47c9e4a535c5.gif)

### Animated gif showing of what's happening using the plugin.
![vokoscreen-2020-07-09_00-16-53](https://user-images.githubusercontent.com/28985314/86996724-58e82080-c17a-11ea-8d17-ac58ba0e6a3a.gif)

**Desktop (please complete the following information):**
Blender 2.83, Ubuntu 18.04, Blender Cad Transforms 0.0.8

Great ad-don by the way!!!

**Comment by s-leger** [comment]
Hit TAB to change the number of axis the scale operation must handle at once.
https://youtu.be/TWEoZghkalc?t=2216

**Comment by stillpointx** [comment]
Thanks!!!
