### ISSUE TITLE
Report: Error when trying to turn on addon

### ISSUE THREAD

**Issue by Blw-h** [s-leger/blender_cad_transforms#22]
I downloaded the zip file from GitHub, loaded it into Blender, but when I try and activate it it shows this message.

![image](https://user-images.githubusercontent.com/68744739/88408399-1be67580-cd99-11ea-8817-de74edf3d924.png)

Please help. Thanks.

**Comment by Blw-h** [comment]
I was trying to install it on 2.80, I installed 2.83 and it works fantastically. Thanks

**Comment by s-leger** [comment]
yep, 2.81 is minimal requirement for 0.0.8 release
