### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by Moult** [s-leger/blender_cad_transforms#23]
After downloading from Gumtree, I see `__init__.py` says its GPL. Which GPL is this, and is it possible to put the code in this repo?

**Comment by s-leger** [comment]
Code is [gpl v3](https://github.com/s-leger/blender_cad_transforms/blob/master/LICENSE) 
It is available for free on gumroad, storing in public github means the end of development as unfortunately the donation rate is almost nil.

**Comment by Moult** [comment]
Cheers :) Thanks for the clarification!
