### ISSUE TITLE
default select method from 'tweak' to 'select box' while in 'Cad Transform' mode

### ISSUE THREAD

**Issue by theoryshaw** [s-leger/blender_cad_transforms#28]
Is it possible to change the default select method from 'tweak' to 'select box' while in 'Cad Transform' mode?  Or at least a preference option. 

Maybe I'm missing something.

![image](https://user-images.githubusercontent.com/507113/92013803-e0ce4f00-ed13-11ea-8e6f-9b18f388c0c8.png)

**Comment by s-leger** [comment]
CAD Transform is a "tool" so select tool is disabled when active.
Use "B" key to select using a box.

**Comment by theoryshaw** [comment]
Thanks Stephen, 
Would it be possible to either have CAD Transform use the 'select box' as the default mode, or at least a preference one could set.  Just trying to avoid hitting 'B' for every action I do.

**Comment by Michaelknubben** [comment]
It'd be ideal to have a dropdown to select what happens on drag, as in the default Blender Move, Rotate and Scale tools: 
![afbeelding](https://user-images.githubusercontent.com/27723800/120620637-75114200-c45d-11eb-8955-823d0351e2e0.png)

**Comment by s-leger** [comment]
Next version default to select box action without active transform operator.  
Will wait for users feedback / bug reports for 0.93.0 for like a month or so, and then relase 0.93.1

**Comment by theoryshaw** [comment]
![spin](https://user-images.githubusercontent.com/507113/123549782-12475980-d730-11eb-9eda-68ca94705611.gif)
