### ISSUE TITLE
Feature request: Let the user scale an object with locked aspect ratios by entering the new value of one dimension.  

### ISSUE THREAD

**Issue by raindropsfromsky** [s-leger/blender_cad_transforms#31]
Let the user can lock the aspect ratio of the object while scaling and enter a new value in one of the three dimensions. 
(In other words, he is not expected to enter a multiplier factor.)

The other two dimensions should automatically get multiplied by the same factor.

For example, assume that we have a cube with LxBxH dimensions of 2x3x5 units.
The user wants to make the Height equal to 7.5 unit, but lock the aspect ratios for the other two dimensions.

Here, the addon calculates that the equivalent multiplier is 7.5/5=1.5.
So it multiplies all dimensions by 1.5.
Now the new dimensions of the cube is 3x4.5x7.5.

**Comment by s-leger** [comment]
https://www.youtube.com/watch?v=TWEoZghkalc&t=2212s
