### ISSUE TITLE
Feature request: Let the user select multiple objects and align them, or distribute them with one click

### ISSUE THREAD

**Issue by raindropsfromsky** [s-leger/blender_cad_transforms#32]
This feature is meant to be used when the user has selected his view along one of the major axes. In other words, it works best when the view is front/back/left/right/top/bottom.

let the user select a few objects (may have dissimilar sizes and shapes), and then align or distribute them in space with one keystroke.

This facility is given in LibreOffice Impress.

![image](https://user-images.githubusercontent.com/9047168/94359100-afeafb00-00c2-11eb-94df-b2260db0a362.png)

The left panel shows the options for aligning the objects.
The right panel shows the options for distributing the objects.

**Comment by s-leger** [comment]
Hi,
There are add-ons dedicated to this task.
Maybe MACHIN3Tools.
