### ISSUE TITLE
Feature request: Please provide an option to move a 3D cursor with snap.

### ISSUE THREAD

**Issue by satabol** [s-leger/blender_cad_transforms#36]
Spin instrument in edit mode use 3DCursor. But there is no default method to set correct position of 3DCursor quickly. But with your instrument this action may be simpler?

**Comment by s-leger** [comment]
There is available addon to actually manipulate cursor providing this feature.

**Comment by satabol** [comment]
Sorry. It is my mistake. I skip some part of your video guide - "5. Only Origin". It is very close to what I want.
