### ISSUE TITLE
entering in inches, and a combination of feet and inches

### ISSUE THREAD

**Issue by theoryshaw** [s-leger/blender_cad_transforms#40]
being able to type in inch dimensions.
for example: ```6 3/16"```

Also the ability to type in a combine of feet and inches like...
```3' 5 7/32"```

maybe this can be done, and i'm missing something.

**Comment by s-leger** [comment]
should be possible,
4'2/3" does work for me

**Comment by theoryshaw** [comment]
what about ```4' 0 3/16"``` for example?

**Comment by s-leger** [comment]
without the 0 !

**Comment by theoryshaw** [comment]
Thanks Stephen. 
See the following conversation for future passerby's
https://matrix.to/#/!FORymwGwqHJnZDpjSI:matrix.org/$B-2rk7FzLDxyT4lMYydFLbFBALnxOYwpxa9juZtRN5A?via=matrix.org&via=t2bot.io&via=tchncs.de
