### ISSUE TITLE
During grab operation, the normal flips to the wrong side, the user is unable to flip it back.

### ISSUE THREAD

**Issue by raindropsfromsky** [s-leger/blender_cad_transforms#5]
Not sure whether this is a bug, or I am doing something wrongly:

I am trying to land the "house" on a flat box. So initially I used pressed **E** (**Edge** mode). 
Then I selected the "house", and pressed G (grab) and released LMB. 
While dragging, I pressed **N** to enter **Normals** mode.

When the "house" nears the box, the normals flip every time. As a result, the "house" lands upside down. I cannot manipulate to keep the normal upright. I cannot flip the normal also.

The screenshot shows "before-after" picture. (The Addon's toolbar is also shown for clarity)
![image](https://user-images.githubusercontent.com/9047168/83944229-76df0000-a81f-11ea-996b-15fb3196f2de.png)

**Desired:**  
Let the user flip the normal manually.

**Comment by s-leger** [comment]
This is more a WIP thing, and will be fixed in next release.

**Comment by raindropsfromsky** [comment]
oh thanks!
