### ISSUE TITLE
Overlays break Blender corners

### ISSUE THREAD

**Issue by Pixel48** [s-leger/blender_cad_transforms#52]
When add-on show it's overlay, region borders disappear and region corners are barely visible, which makes it hart to manage regions. Blender can't redraw regions properly until blender full restart

![beaking_corners](https://user-images.githubusercontent.com/42846410/110651615-e1acd580-81bb-11eb-917f-7358aef14632.gif)

**Comment by Pixel48** [comment]
Is there any way to prevent this or fix it on the fly?

**Comment by s-leger** [comment]
You may give 0.0.9 version a try, not able to narrow down that issue so far.

**Comment by gerciowski** [comment]
> 
> 
> You may give 0.0.9 version a try, not able to narrow down that issue so far.

Version 0.0.9 gives the same glitch:
![cad transform issue](https://user-images.githubusercontent.com/85231622/120476514-f2c84580-c3aa-11eb-9e87-762b3e214bf8.jpg)

**Comment by s-leger** [comment]
Should be fixed in 0.92 and 0.93 versions.
