### ISSUE TITLE
CAD button not available in Edit Mode

### ISSUE THREAD

**Issue by shnlmn** [s-leger/blender_cad_transforms#60]
I am not seeing the CAD button when in edit mode, but it works fine in object mode
Blender 2.93.0
slcad_transform_0.93.1
![image](https://user-images.githubusercontent.com/11766000/123173487-8a153b80-d433-11eb-971a-39b00046a86f.png)
![image](https://user-images.githubusercontent.com/11766000/123173505-8f728600-d433-11eb-8ba5-531c5aa64aa8.png)
![image](https://user-images.githubusercontent.com/11766000/123173585-ae711800-d433-11eb-90c4-bc01c3855b84.png)

**Comment by s-leger** [comment]
see #59
