### ISSUE TITLE
Snap does not work in edit mode on Blender 3.0.0

### ISSUE THREAD

**Issue by meikasahara** [s-leger/blender_cad_transforms#61]
Blender Version 3.0.0
CAD Transform Version 0.93.2
Linux

Snap does not work in edit mode on Blender 3.0.0 using CAD transforms version 0.93.2 beta or 0.93.1. It works fine on Blender 2.93 using version 0.93.1.

**Comment by s-leger** [comment]
re-download

**Comment by meikasahara** [comment]
After re-downloading the slcad_transform_0.93.2.beta2 from gumroad, the issue still persists in edit mode. Additionally, the transformations do not appear or get executed.
