### ISSUE TITLE
CAD Transforms 2.93.2 doesn't work with Blender 2.93.6, Windows system

### ISSUE THREAD

**Issue by blenderpnn** [s-leger/blender_cad_transforms#73]
Hi,
I installed and removed several different downloads of CAD Transforms and none of them will work at all when I press "g" "s" or "r".  
I see all the icons and I active the button so that is is highlight blue.  I watched videos on how to use it but can't seem to get it to work.
Thank you for any help!
Ke
![image](https://user-images.githubusercontent.com/97196516/148290824-03a0e1ce-bd73-49cc-9c17-60ea583dd821.png)

**Comment by s-leger** [comment]
Under blender 2.93.x you must setup slcad_transform_0.93.1.hotfix.2

**Comment by blenderpnn** [comment]
I found it. thank you!
