### ISSUE TITLE
Snapping to Grid shifts to non-scene default

### ISSUE THREAD

**Issue by firebert85** [s-leger/blender_cad_transforms#87]
Seen only a couple other posts re: grid snap.

What I'm seeing:
 when I toggle the addon's grid snap, it clearly shifts to something other than the grid that is standard for the scene. Is there a shortcut I can't see that lets me switch between different grid spaces? The gumroad page for the addon does say "Grid - local / global / user defined" but I see no where to make that selection. Is the addon not synced to the scenes units?

**Comment by s-leger** [comment]
The shortcut is a toggle, starting in local object mode, then global (world) mode, then user defined space.
