### ISSUE TITLE
won't activate in blender 3.5

### ISSUE THREAD

**Issue by klgc2** [s-leger/blender_cad_transforms#96]
CAD Transform (slcad_transform_0.95.0.zip) will load but will not activate in blender 3.5. It does load and activate in blender 3.4.1

**Comment by s-leger** [comment]
Unable to repro here, any error traceback ?
![CT_blender3 5](https://user-images.githubusercontent.com/7442572/226356478-77d2b535-c9b3-4c53-a2fd-7ac5c69edfbe.png)
