### ISSUE TITLE
problems installing in macOs moterrey

### ISSUE THREAD

**Issue by elgeografo** [s-leger/blender_cad_transforms#99]
<img width="836" alt="Screenshot 2023-04-07 at 16 50 09" src="https://user-images.githubusercontent.com/7286936/230628979-013a902b-1d78-4d42-ba16-11692f8b103a.png">

Hi I have this error trying to install it my blender version is 3.5.0 and I'm using a macOS Monterrey. is there any incompatibility problem with macOs?

**Comment by s-leger** [comment]
https://github.com/s-leger/blender_cad_transforms/issues/97
